#!/usr/bin/env python3

import os
import sys

known_hosts = os.path.join(os.getenv("HOME"), ".ssh/known_hosts")

if len(sys.argv) < 2:
    print("Argument required")
    sys.exit(1)

line = int(sys.argv[1])

with open(known_hosts, 'r') as f:
    lines = f.readlines()

del(lines[line - 1])
data = "".join(lines)

with open(known_hosts, 'w') as f:
    f.write(data)
